# Generated by Django 4.2.17 on 2024-12-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathertimestamp',
            name='city_name',
        ),
    ]
